# Generated by Django 6.0.3 on 2026-03-31 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('issue_type', models.CharField(choices=[('water_leak', 'Water Leak'), ('electricity', 'Electricity Fault'), ('pothole', 'Pothole'), ('waste', 'Waste Collection'), ('other', 'Other')], max_length=20)),
                ('location', models.CharField(max_length=300)),
                ('status', models.CharField(choices=[('reported', 'Reported'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], default='reported', max_length=20)),
                ('priority', models.IntegerField(default=1, help_text='1=Low, 2=Medium, 3=High')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reporter_name', models.CharField(max_length=150)),
                ('reporter_email', models.EmailField(max_length=254)),
                ('image', models.ImageField(blank=True, null=True, upload_to='issues/')),
            ],
            options={
                'verbose_name_plural': 'Issues',
                'ordering': ['-created_at'],
            },
        ),
    ]
